# Generated by Django 3.2.4 on 2021-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inglizcha', models.CharField(max_length=130, verbose_name='Inglizcha')),
                ('uzbekcha', models.CharField(max_length=130, verbose_name='Uzbekcha')),
            ],
        ),
    ]
